apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backendService.port }}
      targetPort: {{ .Values.backendService.targetPort }}
  type: {{ .Values.backendService.type }}
