apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.frontendService.selector }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontendService.port }}
      targetPort: {{ .Values.frontendService.targetPort }}
  type: {{ .Values.frontendService.type }}
