apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.mongo.name }}
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
