apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.mongo.username | b64enc }}
  password: {{ .Values.mongo.password | b64enc }}
