apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: three-tier
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
  type: ClusterIP